# See https://pre-commit.com
# Install: pip install pre-commit && pre-commit install
repos:
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        files: ^(apps/backend|libs)/.*\.py$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^apps/frontend/src/.*\.(js|jsx|json|css)$
